### ISSUE TITLE
BUG: KeyError raised when using EPICS areaDetector ADSimDetector

### ISSUE THREAD

**Issue by prjemian** [NSLS-II/suitcase#34]
When using AD 2.6 and ADSimDetector 2.4, a [KeyError was raised](https://github.com/BCDA-APS/use_bluesky/blob/2bcf4a94958fffa4565092284a90b7a5d90a63ca/plans/standlone.py#L224).  The containing file describes the full setup.  The related plan is in the other file in the same directory.

**Comment by prjemian** [comment]
Assign this one to me.

**Comment by tacaswell** [comment]
That looks like a mis-match between the descriptor and the events coming from the SimDetector

**Comment by prjemian** [comment]
Here is the Traceback

<details>

    Traceback (most recent call last):
      File "/home/prjemian/Documents/eclipse/use_bluesky/plans/standlone.py", line 205, in <module>
        RE(tomo_plan, tomo_callbacks, md=dict(developer=True))
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/run_engine.py", line 599, in __call__
        raise exc
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/run_engine.py", line 1007, in _run
        raise err
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/run_engine.py", line 905, in _run
        msg = self._plan_stack[-1].send(resp)
      File "/home/prjemian/Documents/eclipse/use_bluesky/plans/interlace_tomo.py", line 172, in interlace_tomo_scan
        return (yield from inner_scan())
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/plans.py", line 47, in dec_inner
        return (yield from plan)
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/plans.py", line 1510, in stage_wrapper
        return (yield from finalize_wrapper(inner(), unstage_devices()))
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/plans.py", line 1025, in finalize_wrapper
        ret = yield from plan
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/plans.py", line 1508, in inner
        return (yield from plan)
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/plans.py", line 47, in dec_inner
        return (yield from plan)
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/plans.py", line 874, in run_wrapper
        rs_uid = yield from close_run()
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/plans.py", line 967, in close_run
        return (yield Msg('close_run'))
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/run_engine.py", line 956, in _run
        response = yield from coro(msg)
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/run_engine.py", line 1211, in _close_run
        yield from self.emit(DocumentNames.stop, doc)
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/asyncio/coroutines.py", line 206, in coro
        res = func(*args, **kw)
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/run_engine.py", line 1969, in emit
        self.dispatcher.process(name, doc)
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/run_engine.py", line 1981, in process
        exceptions = self.cb_registry.process(name, name.name, doc)
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/utils.py", line 271, in process
        func(*args, **kwargs)
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/bluesky/utils.py", line 352, in __call__
        return mtd(*args, **kwargs)
      File "/home/prjemian/Documents/eclipse/use_bluesky/plans/standlone.py", line 170, in write_nexus_callback
        suitcase.nexus.export(header, filename, mds, use_uid=False)
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/suitcase/nexus.py", line 178, in export
        timestamps = [e['timestamps'][safename] for e in events]
      File "/home/prjemian/Apps/BlueSky/lib/python3.5/site-packages/suitcase/nexus.py", line 178, in <listcomp>
        timestamps = [e['timestamps'][safename] for e in events]
    KeyError: '_13SIM1__cam_peak_start_peak_start_y'

</details>
